<a href="https://colab.research.google.com/github/kxrrym03/FIFA/blob/main/FIFA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
from google.colab import files
uploaded = files.upload()

Saving test.csv to test (1).csv

In [4]:
df = pd.read_csv('test.csv')
df.shape

(48, 24)

In [5]:
df.head()

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,world_cup_participations_before,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist
0,2026,France,Europe,0,85,32,25,6,7,2,...,16,10,8,9,7,4,NaN,NaN,NaN,NaN
1,2026,Spain,Europe,0,104,32,29,2,8,1,...,16,11,9,6,2,1,NaN,NaN,NaN,NaN
2,2026,Argentina,South America,0,80,14,30,4,3,3,...,18,15,10,10,6,6,NaN,NaN,NaN,NaN
3,2026,England,Europe,0,82,23,26,6,7,1,...,16,13,8,10,3,1,NaN,NaN,NaN,NaN
4,2026,Portugal,Europe,0,98,31,26,5,7,0,...,8,5,4,3,2,0,NaN,NaN,NaN,NaN

In [6]:
df.tail()

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,world_cup_participations_before,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist
43,2026,Cape Verde,Africa,0,46,39,16,10,12,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
44,2026,Ghana,Africa,0,46,42,12,13,9,0,...,4,2,2,1,0,0,NaN,NaN,NaN,NaN
45,2026,Cura?o,North America,0,55,39,12,10,10,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
46,2026,Haiti,North America,0,71,37,16,8,8,0,...,1,0,0,0,0,0,NaN,NaN,NaN,NaN
47,2026,New Zealand,Oceania,0,63,32,13,12,6,0,...,2,0,0,0,0,0,NaN,NaN,NaN,NaN

In [7]:
df.isnull().sum()

version                             0
team                                0
continent                           0
is_host                             0
goals_scored_last_4y                0
goals_received_last_4y              0
wins_last_4y                        0
losses_last_4y                      0
draws_last_4y                       0
world_cup_titles_before             0
squad_total_market_value_eur        0
fifa_rank_pre_tournament            0
fifa_points_pre_tournament          0
squad_avg_age                       0
world_cup_participations_before     0
groups_passed_before                0
round16_before                      0
quarterfinals_before                0
semifinals_before                   0
finals_before                       0
winner                             48
finalist                           48
semi_finalist                      48
quarter_finalist                   48
dtype: int64

In [8]:
df.drop(['winner', 'finalist', 'semi_finalist', 'quarter_finalist'], axis=1, inplace=True)
print(df.shape)

(48, 20)

In [9]:
df.isnull().sum()

version                            0
team                               0
continent                          0
is_host                            0
goals_scored_last_4y               0
goals_received_last_4y             0
wins_last_4y                       0
losses_last_4y                     0
draws_last_4y                      0
world_cup_titles_before            0
squad_total_market_value_eur       0
fifa_rank_pre_tournament           0
fifa_points_pre_tournament         0
squad_avg_age                      0
world_cup_participations_before    0
groups_passed_before               0
round16_before                     0
quarterfinals_before               0
semifinals_before                  0
finals_before                      0
dtype: int64

In [ ]:
for col in df.select_dtypes(include='object').columns:
    print(f'Column {col}: {df[col].nunique()} unique values')
    print(df[col].unique())
    print('\n')

In [10]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 20 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   version                          48 non-null     int64
 1   team                             48 non-null     object
 2   continent                        48 non-null     object
 3   is_host                          48 non-null     int64
 4   goals_scored_last_4y             48 non-null     int64
 5   goals_received_last_4y           48 non-null     int64
 6   wins_last_4y                     48 non-null     int64
 7   losses_last_4y                   48 non-null     int64
 8   draws_last_4y                    48 non-null     int64
 9   world_cup_titles_before          48 non-null     int64
 10  squad_total_market_value_eur     48 non-null     int64
 11  fifa_rank_pre_tournament         48 non-null     int64
 12  fifa_points_pre_tournament       48 non-null     float64
 13  squad_avg_age                    48 non-null     float64
 14  world_cup_participations_before  48 non-null     int64
 15  groups_passed_before             48 non-null     int64
 16  round16_before                   48 non-null     int64
 17  quarterfinals_before             48 non-null     int64
 18  semifinals_before                48 non-null     int64
 19  finals_before                    48 non-null     int64
dtypes: float64(2), int64(16), object(2)
memory usage: 7.6+ KB

In [13]:
df.describe()

,version,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,squad_total_market_value_eur,fifa_rank_pre_tournament,fifa_points_pre_tournament,squad_avg_age,world_cup_participations_before,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before
count,48.0,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,4.800000e+01,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000
mean,2026.0,0.062500,72.395833,37.604167,21.354167,8.604167,9.854167,0.375000,3.117183e+08,32.520833,1579.992083,27.206250,7.041667,4.062500,3.020833,2.437500,1.479167,0.708333
std,0.0,0.244623,18.037478,12.316292,5.923231,4.150056,3.614331,1.064415,3.450467e+08,23.819346,156.617330,1.144907,5.946422,5.187572,3.479359,4.078518,2.835861,1.761990
min,2026.0,0.000000,29.000000,14.000000,9.000000,2.000000,3.000000,0.000000,5.300000e+06,1.000000,1281.570000,24.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2026.0,0.000000,63.000000,30.000000,17.500000,6.000000,7.000000,0.000000,3.762500e+07,13.750000,1475.097500,26.575000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2026.0,0.000000,72.000000,34.500000,21.500000,8.000000,9.000000,0.000000,1.905750e+08,27.500000,1572.465000,27.100000,6.000000,2.000000,2.000000,0.500000,0.000000,0.000000
75%,2026.0,0.000000,82.250000,42.000000,26.000000,11.250000,12.000000,0.000000,4.372125e+08,47.000000,1690.015000,27.925000,11.000000,7.250000,5.000000,3.000000,2.000000,0.000000
max,2026.0,1.000000,110.000000,70.000000,37.000000,20.000000,20.000000,5.000000,1.300000e+09,85.000000,1877.320000,29.300000,22.000000,20.000000,12.000000,17.000000,13.000000,8.000000

In [14]:
df.dtypes

version                              int64
team                                object
continent                           object
is_host                              int64
goals_scored_last_4y                 int64
goals_received_last_4y               int64
wins_last_4y                         int64
losses_last_4y                       int64
draws_last_4y                        int64
world_cup_titles_before              int64
squad_total_market_value_eur         int64
fifa_rank_pre_tournament             int64
fifa_points_pre_tournament         float64
squad_avg_age                      float64
world_cup_participations_before      int64
groups_passed_before                 int64
round16_before                       int64
quarterfinals_before                 int64
semifinals_before                    int64
finals_before                        int64
dtype: object